# Generated by Django 3.2 on 2023-07-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='landImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='squareImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tallImage',
        ),
    ]
