# Generated by Django 3.2 on 2023-07-17 09:47

import cloudinary.models
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20230717_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='landImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='landImage'),
        ),
        migrations.AddField(
            model_name='image',
            name='squareImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='squareImage'),
        ),
        migrations.AddField(
            model_name='image',
            name='tallImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='tallImage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 7, 17, 9, 47, 21, 804096, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
